# Generated by Django 6.0.7 on 2026-07-28 09:37

import apps.finance.models.receipt
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], max_length=10)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Cor hexadecimal inválida.')])),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('period', models.CharField(choices=[('MONTHLY', 'Mensal'), ('YEARLY', 'Anual'), ('CUSTOM', 'Personalizado')], default='MONTHLY', max_length=20, verbose_name='Período')),
                ('start_date', models.DateField(verbose_name='Data inicial')),
                ('end_date', models.DateField(verbose_name='Data final')),
                ('alert_threshold', models.DecimalField(decimal_places=2, default=80, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Limite de alerta (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='finance.category')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('account_type', models.CharField(choices=[('BANK', 'Banco'), ('CASH', 'Dinheiro'), ('CREDIT_CARD', 'Cartão de Crédito'), ('INVESTMENT', 'Investimento'), ('OTHER', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Inicial')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('institution', models.CharField(blank=True, max_length=100, verbose_name='Instituição')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Número da Conta')),
                ('agency_number', models.CharField(blank=True, max_length=20, verbose_name='Agência')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Para contas de crédito', max_digits=12, null=True, verbose_name='Limite de Crédito')),
                ('closing_day', models.PositiveSmallIntegerField(blank=True, help_text='Dia de fechamento da fatura (cartão de crédito)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Fechamento')),
                ('due_day', models.PositiveSmallIntegerField(blank=True, help_text='Dia de vencimento (cartão de crédito)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta Financeira',
                'verbose_name_plural': 'Contas Financeiras',
                'db_table': 'finance_financial_account',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor alvo')),
                ('saved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor economizado')),
                ('start_date', models.DateField(verbose_name='Data Início')),
                ('target_date', models.DateField(verbose_name='Data Alvo')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('ACHIEVED', 'Alcançada'), ('FAILED', 'Falha'), ('CANCELED', 'Cancelada')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('priority', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Prioridade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='finance.category')),
                ('related_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='finance.financialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-priority', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa'), ('TRANSFER', 'Transferência')], max_length=20, verbose_name='Tipo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('frequency', models.CharField(choices=[('DAILY', 'Diário'), ('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quinzenal'), ('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=20, verbose_name='Frequência')),
                ('start_date', models.DateField(verbose_name='Data inicial')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data final')),
                ('next_execution', models.DateField(verbose_name='Próxima execução')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_transactions', to='finance.financialaccount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_transactions', to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação recorrente',
                'verbose_name_plural': 'Transações recorrentes',
                'ordering': ['next_execution'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('color', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor hexadecimal inválida.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa'), ('TRANSFER', 'Transferência')], max_length=10, verbose_name='Tipo')),
                ('date', models.DateField(verbose_name='Data')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Concluída'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('bank_statement_id', models.CharField(blank=True, help_text='ID da transação no extrato bancário', max_length=100, verbose_name='ID Extrato Bancário')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='Conciliado em')),
                ('installment_number', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número da Parcela')),
                ('total_installments', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de Parcelas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.financialaccount')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.category')),
                ('parent_transaction', models.ForeignKey(blank=True, help_text='Transação pai para parcelamentos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments', to='finance.transaction')),
                ('related_transaction', models.ForeignKey(blank=True, help_text='Transação relacionada (para transferências)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to='finance.transaction')),
                ('tags', models.ManyToManyField(blank=True, related_name='transactions', to='finance.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.finance.models.receipt.receipt_upload_path, verbose_name='Arquivo')),
                ('file_hash', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Hash do Arquivo')),
                ('document_type', models.CharField(choices=[('RECEIPT', 'Recibo'), ('INVOICE', 'Nota Fiscal'), ('OTHER', 'Outro')], default='RECEIPT', max_length=20, verbose_name='Tipo do Documento')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor')),
                ('supplier_document', models.CharField(blank=True, max_length=20, verbose_name='Documento do Fornecedor')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('ocr_status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falha')], default='PENDING', max_length=20, verbose_name='Status do OCR')),
                ('ocr_processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('ocr_raw_text', models.TextField(blank=True, verbose_name='Texto OCR Bruto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='finance.transaction', verbose_name='Transação')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['type'], name='finance_cat_type_82bb7e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='finance_cat_is_acti_a413c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'type'), name='unique_category_per_user'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'start_date', 'end_date'), name='unique_budget_period'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['account_type'], name='finance_fin_account_b8769c_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['is_active'], name='finance_fin_is_acti_80b2b3_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['user', 'is_active'], name='finance_fin_user_id_291b0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_account_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['status'], name='finance_goa_status_c3bc10_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['target_date'], name='finance_goa_target__9aaf06_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='finance_goa_user_id_09c835_idx'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_goal_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['next_execution'], name='finance_rec_next_ex_72de31_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['is_active'], name='finance_rec_is_acti_1a186e_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'is_active'], name='finance_rec_user_id_6f7b8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringtransaction',
            constraint=models.UniqueConstraint(fields=('user', 'description', 'account', 'frequency'), name='unique_recurring_transaction'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'name'], name='finance_tag_user_id_936185_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_tag_per_user'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='finance_tra_user_id_3294c0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='finance_tra_user_id_be5f56_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'account'], name='finance_tra_user_id_f167d5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='finance_tra_status_0941b9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'type'], name='finance_tra_date_d6ad5c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['related_transaction'], name='finance_tra_related_e0f13b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['parent_transaction'], name='finance_tra_parent__976815_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status', 'date'], name='finance_tra_user_id_237a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['transaction'], name='finance_rec_transac_717f43_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['ocr_status'], name='finance_rec_ocr_sta_8e230b_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['supplier_name'], name='finance_rec_supplie_f5ff03_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['ocr_status', 'created_at'], name='finance_rec_ocr_sta_41fab6_idx'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='receipt_total_amount_positive'),
        ),
    ]
