# Generated by Django 6.0.7 on 2026-07-28 09:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='receipt',
            name='receipt_total_amount_positive',
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='finance_rec_transac_717f43_idx',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total'),
        ),
    ]
