# Generated by Django 6.0.7 on 2026-07-27 10:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('type', models.CharField(choices=[('BANK', 'Banco'), ('CASH', 'Dinheiro'), ('CREDIT_CARD', 'Cartão de Crédito'), ('INVESTMENT', 'Investimento'), ('OTHER', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Inicial')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('institution', models.CharField(blank=True, max_length=100, verbose_name='Instituição')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Número da Conta')),
                ('agency_number', models.CharField(blank=True, max_length=20, verbose_name='Agência')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Para contas de crédito', max_digits=12, null=True, verbose_name='Limite de Crédito')),
                ('closing_day', models.PositiveSmallIntegerField(blank=True, help_text='Dia de fechamento da fatura (cartão de crédito)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Fechamento')),
                ('due_day', models.PositiveSmallIntegerField(blank=True, help_text='Dia de vencimento (cartão de crédito)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta Financeira',
                'verbose_name_plural': 'Contas Financeiras',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user'], name='finance_fin_user_id_a3a438_idx'), models.Index(fields=['type'], name='finance_fin_type_be79fe_idx'), models.Index(fields=['is_active'], name='finance_fin_is_acti_91a817_idx')],
            },
        ),
    ]
