# Generated by Django 6.0.7 on 2026-07-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financialaccount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='financialaccount',
            new_name='financial_a_user_id_f62780_idx',
            old_name='finance_fin_user_id_a3a438_idx',
        ),
        migrations.RenameIndex(
            model_name='financialaccount',
            new_name='financial_a_type_cbe140_idx',
            old_name='finance_fin_type_be79fe_idx',
        ),
        migrations.RenameIndex(
            model_name='financialaccount',
            new_name='financial_a_is_acti_1b1be8_idx',
            old_name='finance_fin_is_acti_91a817_idx',
        ),
        migrations.AlterModelTable(
            name='financialaccount',
            table='financial_account',
        ),
    ]
