# Generated by Django 6.0.7 on 2026-07-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_finance_fin_user_id_a3a438_idx_financial_a_user_id_f62780_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='financialaccount',
            new_name='finance_fin_user_id_ead6f8_idx',
            old_name='financial_a_user_id_f62780_idx',
        ),
        migrations.RenameIndex(
            model_name='financialaccount',
            new_name='finance_fin_type_47ba3f_idx',
            old_name='financial_a_type_cbe140_idx',
        ),
        migrations.RenameIndex(
            model_name='financialaccount',
            new_name='finance_fin_is_acti_80b2b3_idx',
            old_name='financial_a_is_acti_1b1be8_idx',
        ),
        migrations.AlterModelTable(
            name='financialaccount',
            table='finance_financial_account',
        ),
    ]
