# Generated by Django 6.0.7 on 2026-07-27 10:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa'), ('TRANSFER', 'Transferência')], max_length=10, verbose_name='Tipo')),
                ('date', models.DateField(verbose_name='Data')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Concluída'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('bank_statement_id', models.CharField(blank=True, help_text='ID da transação no extrato bancário', max_length=100, verbose_name='ID Extrato Bancário')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='Conciliado em')),
                ('installment_number', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número da Parcela')),
                ('total_installments', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de Parcelas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.financialaccount')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.category')),
                ('parent_transaction', models.ForeignKey(blank=True, help_text='Transação pai para parcelamentos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments', to='finance.transaction')),
                ('related_transaction', models.ForeignKey(blank=True, help_text='Transação relacionada (para transferências)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to='finance.transaction')),
                ('tags', models.ManyToManyField(blank=True, related_name='transactions', to='finance.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='finance_tra_user_id_3294c0_idx'), models.Index(fields=['user', 'category'], name='finance_tra_user_id_be5f56_idx'), models.Index(fields=['user', 'account'], name='finance_tra_user_id_f167d5_idx'), models.Index(fields=['status'], name='finance_tra_status_0941b9_idx'), models.Index(fields=['date', 'type'], name='finance_tra_date_d6ad5c_idx'), models.Index(fields=['related_transaction'], name='finance_tra_related_e0f13b_idx'), models.Index(fields=['parent_transaction'], name='finance_tra_parent__976815_idx')],
            },
        ),
    ]
