# Generated by Django 6.0.7 on 2026-07-27 11:32

import apps.finance.models.receipt
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_transaction_amount_alter_transaction_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.finance.models.receipt.receipt_upload_path, verbose_name='Arquivo')),
                ('file_hash', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Hash do Arquivo')),
                ('document_type', models.CharField(choices=[('RECEIPT', 'Recibo'), ('INVOICE', 'Nota Fiscal'), ('OTHER', 'Outro')], default='RECEIPT', max_length=20, verbose_name='Tipo do Documento')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor')),
                ('supplier_document', models.CharField(blank=True, max_length=20, verbose_name='Documento do Fornecedor')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('ocr_status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falha')], default='PENDING', max_length=20, verbose_name='Status do OCR')),
                ('ocr_processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('ocr_raw_text', models.TextField(blank=True, verbose_name='Texto OCR Bruto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='finance.transaction', verbose_name='Transação')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'indexes': [models.Index(fields=['transaction'], name='finance_rec_transac_717f43_idx'), models.Index(fields=['ocr_status'], name='finance_rec_ocr_sta_8e230b_idx'), models.Index(fields=['supplier_name'], name='finance_rec_supplie_f5ff03_idx'), models.Index(fields=['ocr_status', 'created_at'], name='finance_rec_ocr_sta_41fab6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='receipt_total_amount_positive')],
            },
        ),
    ]
