# Generated by Django 6.0.7 on 2026-07-28 09:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor alvo')),
                ('saved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor economizado')),
                ('start_date', models.DateField(verbose_name='Data Início')),
                ('target_date', models.DateField(verbose_name='Data Alvo')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('ACHIEVED', 'Alcançada'), ('FAILED', 'Falha'), ('CANCELED', 'Cancelada')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('priority', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Prioridade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-priority', 'target_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='financialaccount',
            name='finance_fin_user_id_ead6f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialaccount',
            name='finance_fin_type_47ba3f_idx',
        ),
        migrations.RenameField(
            model_name='financialaccount',
            old_name='type',
            new_name='account_type',
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['account_type'], name='finance_fin_account_b8769c_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['user', 'is_active'], name='finance_fin_user_id_291b0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'type'), name='unique_category_per_user'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_account_name_per_user'),
        ),
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='finance.category'),
        ),
        migrations.AddField(
            model_name='goal',
            name='related_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['status'], name='finance_goa_status_c3bc10_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['target_date'], name='finance_goa_target__9aaf06_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='finance_goa_user_id_09c835_idx'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_goal_name_per_user'),
        ),
    ]
