# Generated by Django 6.0.7 on 2026-07-28 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_goal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_template', models.JSONField(verbose_name='Template da transação')),
                ('frequency', models.CharField(choices=[('DAILY', 'Diário'), ('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quinzenal'), ('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=20, verbose_name='Frequência')),
                ('start_date', models.DateField(verbose_name='Data inicial')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data final')),
                ('next_execution', models.DateField(verbose_name='Próxima execução')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação recorrente',
                'verbose_name_plural': 'Transações recorrentes',
                'db_table': 'finance_recurring_transaction',
                'ordering': ['next_execution'],
                'indexes': [models.Index(fields=['next_execution'], name='finance_rec_next_ex_71fd4e_idx'), models.Index(fields=['is_active'], name='finance_rec_is_acti_09643c_idx'), models.Index(fields=['user', 'is_active'], name='finance_rec_user_id_caf2a1_idx')],
            },
        ),
    ]
